version: "3.7"

services:
  nginx:
    image: nginx:1.17.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - osiris-ig-app:/var/www/osiris.arkhn.com
    ports:
      - 8080:8080

  osiris-ig-build:
    image: arkhn/osiris-ig:latest
    volumes:
      - osiris-ig-app:/build/output

volumes:
  osiris-ig-app:
